---
- name: Deploy Java Application
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull the Docker image
      docker_image:
        name: ahmedshalapy805/devops-task
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: devops-task-app
        image: ahmedshalapy805/devops-task:latest
        ports:
          - "8080:8080"
        state: started

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes
