#
#    Copyright 2010-2025 the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

---
- name: Deploy Java Application
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull the Docker image
      docker_image:
        name: ahmedshalapy/devops-task
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: devops-task-app
        image: ahmedshalapy/devops-task:latest
        ports:
          - "8080:8080"
        state: started

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes
